executor: KubernetesExecutor

nodeSelector:
  role: core

logs:
  persistence:
    enabled: false

config:
  api:
    workers: "1"
  kubernetes:
    pod_template_file: "/opt/airflow/k8s/pod_template.yaml"
    namespace: "airflow"
  kubernetes_executor:
    delete_worker_pods: "False"
    delete_worker_pods_on_failure: "False"
  core:
    parallelism: "1"
    dag_concurrency: "1"
    max_active_runs_per_dag: "1"

extraEnvFrom: |
  - secretRef:
      name: secrets-local

webserverSecretKeySecretName: "secrets-local"
fernetKeySecretName: "secrets-local"

postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: latest
    pullPolicy: IfNotPresent


  primary:
    replicas: 1
    nodeSelector:
      role: core
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "4Gi"

apiServer:
  replicas: 1
  service:
    type: ClusterIP
    ports:
      - name: airflow-ui
        port: 8080
        targetPort: 8080
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "2Gi"

createUserJob:
  useHelmHooks: true

webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: "jonas_admin"
    email: "jonaslaya@workmate.cl"
    firstName: "Jonas"
    lastName: "Laya"

scheduler:
  replicas: 1
  nodeSelector:
    role: core
  extraVolumes:
    - name: worker-template-volume
      configMap:
        name: worker-pod-template
  extraVolumeMounts:
    - name: worker-template-volume
      mountPath: "/opt/airflow/k8s"
      readOnly: true
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

triggerer:
  replicas: 1
  nodeSelector:
    role: core
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1.5Gi"

dagProcessor:
  replicas: 1
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "600m"
      memory: "1.5Gi"

statsd:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
