executor: KubernetesExecutor

nodeSelector:
  role: core

postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: latest
    pullPolicy: IfNotPresent

  primary:
    replicas: 1
    nodeSelector:
      role: core
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "4Gi"

apiServer:
  replicas: 1
  service:
    type: ClusterIP
    ports:
      - name: airflow-ui
        port: 8080
        targetPort: 8080
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "2Gi"

scheduler:
  replicas: 1
  nodeSelector:
    role: core
  extraVolumes:
    - name: worker-template-volume
      configMap:
        name: worker-pod-template
  extraVolumeMounts:
    - name: worker-template-volume
      mountPath: "/opt/airflow/k8s"
      readOnly: true
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

triggerer:
  replicas: 1
  nodeSelector:
    role: core
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1.5Gi"

dagProcessor:
  replicas: 1
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "600m"
      memory: "1.5Gi"

statsd:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

env:
  - name: AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE
    value: "/opt/airflow/k8s/pod_template.yaml"

extraEnvFrom: |
  - secretRef:
      name: secrets-local

config:
  kubernetes:
    namespace: airflow
    delete_worker_pods: "False"
    
  core:
    parallelism: "1"
    dag_concurrency: "1"
    max_active_runs_per_dag: "1"