apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

secretGenerator:
  - name: secrets-local
    envs:
      - secrets/airflow.env
      - secrets/dbt.env
    files:
      - OCI_PRIVATE_KEY_CONTENT=secrets/oci/OCI_PRIVATE_KEY_CONTENT.pem
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true