apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      nodeSelector:
        role: core
      containers:
        - name: metabase
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_TYPE
              value: postgres
            - name: MB_DB_DB
              value: postgres
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_USER
              value: postgres
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgres-password
            - name: MB_DB_HOST
              value: airflow-postgresql
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: airflow
spec:
  selector:
    app: metabase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP