apiVersion: v1
kind: Pod
metadata:
  name: dummy-name
spec:
  containers:
    - name: base
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "heavy"
      effect: "NoSchedule"
  nodeSelector:
    role: worker