apiVersion: v1
kind: Pod
metadata:
  name: airflow-worker-template

spec:
  containers:
    - name: base
      image: airflow-crypto:latest
      imagePullPolicy: IfNotPresent

      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "2Gi"

      envFrom:
        - secretRef:
            name: secrets-local

      volumeMounts:
        - name: airflow-tmp
          mountPath: /tmp

  volumes:
    - name: airflow-tmp
      emptyDir:
        sizeLimit: 20Gi

  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "heavy"
      effect: "NoSchedule"

  nodeSelector:
    role: worker

  restartPolicy: Never